=== STScI-JWST/wss_tools/wss_tools/quip/data/quip_operation_file.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xsd:element name="QUIP_OPERATION_FILE">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="CORRECTION_ID" type="xsd:string" />
                <xsd:element name="OPERATION_TYPE">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="THUMBNAIL|FOCUS_SWEEP|SEGMENT_ID|SEGMENT_SEARCH|IMAGE_ARRAY|GLOBAL_ALIGNMENT|FVA_COARSE_MIMF|FVA_FIELD_VIGNETTING_SCAN|IMAGE_STACKING|COARSE_PHASING|PUPIL_IMAGING|FINE_PHASING|MIMF|WAVEFRONT_MAINTENANCE"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="IMAGES" >
                    <xsd:complexType>
                        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                            <xsd:element name="IMAGE_PATH" type="xsd:string" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="OUTPUT" >
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="OUTPUT_DIRECTORY" type="xsd:string" />
                            <xsd:element name="LOG_FILE_PATH" type="xsd:string" />
                            <xsd:element name="OUT_FILE_PATH" type="xsd:string" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="creator" type="xsd:string" use="required"/>
            <xsd:attribute name="time" type="xsd:time" use="required"/>
            <xsd:attribute name="date" type="xsd:date" use="required"/>
            <xsd:attribute name="version" type="xsd:string" use="required"/>
            <xsd:attribute name="operational" type="xsd:boolean" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== STScI-JWST/wss_tools/wss_tools/tests/data/operation_file_001.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QUIP_OPERATION_FILE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" creator="Test" time="19:56:56.934Z" date="2015-01-14Z" version="4.0" operational="false" xsi:noNamespaceSchemaLocation="quip_operation_file.xsd">
    <CORRECTION_ID>R2015011401</CORRECTION_ID>
    <OPERATION_TYPE>MIMF</OPERATION_TYPE>
    <IMAGES>
        <IMAGE_PATH>/path/to/inputs/image001.fits</IMAGE_PATH>
        <IMAGE_PATH>/path/to/inputs/image002.fits</IMAGE_PATH>
    </IMAGES>
    <OUTPUT>
        <OUTPUT_DIRECTORY>/path/to/outputs/</OUTPUT_DIRECTORY>
        <LOG_FILE_PATH>/path/to/outputs/quip_activity_log.xml</LOG_FILE_PATH>
        <OUT_FILE_PATH>/path/to/outputs/quip_out.xml</OUT_FILE_PATH>
    </OUTPUT>
</QUIP_OPERATION_FILE>
